In [55]:
import torch
from torch_geometric.data import Data
import pandas as pd
import os

In [2]:
df = pd.read_excel('../data/DT_File_MAP.xlsx')
df

,Subject,PTID,VISCODE,LABEL,AGE,GENDER,EDUCATION,Node 1,Node 2,Node 3,...,Node 139,Node 140,Node 141,Node 142,Node 143,Node 144,Node 145,Node 146,Node 147,Node 148
0,S177586,005_S_4910,3,AD,81.4,Female,15,1.959,2.047,2.108,...,1.847,2.070,1.573,1.998,2.193,1.976,1.733,1.574,1.838,1.457
1,S185876,005_S_4910,6,AD,81.4,Female,15,1.891,2.048,1.783,...,1.649,2.271,1.594,1.793,2.240,2.562,1.647,1.642,1.837,1.541
2,S177601,005_S_5038,0,AD,81.5,Male,18,2.025,2.048,2.507,...,1.878,2.044,1.886,2.367,2.156,2.163,2.215,2.112,2.066,1.830
3,S184500,005_S_5038,3,AD,81.5,Male,18,2.016,1.964,2.572,...,1.859,2.042,1.784,2.200,2.004,1.904,2.170,1.681,1.929,1.637
4,S191604,005_S_5038,6,AD,81.5,Male,18,2.004,1.907,2.411,...,1.764,2.077,1.768,2.229,2.049,1.900,2.224,2.103,2.014,1.788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S155271,098_S_4506,3,CN,71.5,Male,19,2.140,2.143,2.061,...,1.846,2.541,1.814,2.181,2.360,1.885,2.007,2.226,2.202,2.314
496,S167381,098_S_4506,6,CN,71.5,Male,19,2.145,2.182,2.005,...,1.831,2.606,1.873,2.239,2.363,2.511,1.992,2.298,2.181,2.171
497,S197407,098_S_4506,12,CN,71.5,Male,19,1.990,2.174,2.038,...,1.781,2.498,1.771,2.177,2.094,2.399,1.995,2.333,2.185,2.097
498,S447003,098_S_4506,24,CN,71.5,Male,19,2.134,2.171,2.012,...,1.820,2.558,1.769,2.204,2.140,2.405,2.056,2.368,2.165,1.959
499,S206831,129_S_4371,24,CN,67.7,Male,18,2.306,2.337,1.972,...,1.895,2.554,1.691,2.102,1.895,2.416,1.970,1.954,2.020,1.987

In [10]:
df[df.index==0]["LABEL"].item()

'AD'

In [ ]:
labels = {}
labels['CN'] = 0
labels['EMCI'] = 1
labels['LMCI'] = 2
labels['AD'] = 3

In [16]:
df.shape[0]

500

In [41]:
filepath_r = os.path.join(os.path.join(".","sparsifiaction"),"data")
filepath_r = "./sparsification/data"

In [90]:
for i in range(df.shape[0]):
    print(df[df.index==i]["LABEL"].item())
    if(df[df.index==i]["LABEL"].item() == 'SMC'):
        continue
    y = 
    filename = os.path.join(filepath_r, "%s_fdt_network_matrix_df.csv"%df[df.index==i]["Subject"].item())
    #print(filename)
    
    edge_table = pd.read_csv(filename, sep = "\t")
    edge_table = edge_table[["src", "trg", "nij"]]
    #print(edge_table)
    edge_index = torch.tensor(edge_table[["src", "trg"]].values).transpose(0,1)
    edge_attr = torch.tensor(edge_table[["nij"]].values)
    print(edge_index.size())
    print(edge_attr.size())
           
    x = torch.tensor(df[df.index==i][["Node %d"%(i) for i in range(1,149)]].values).transpose(0,1)
    print(x.size())
    
    break

AD
torch.Size([2, 1017])
torch.Size([1017, 1])
torch.Size([148, 1])

In [77]:
torch.tensor(edge_table[["src", "trg"]].values)
torch.tensor(df[df.index==i][["Node %d"%(i) for i in range(1,149)]].values)

tensor([[1.9590, 2.0470, 2.1080, 2.0860, 2.1190, 2.0680, 2.3310, 2.2250, 2.4590,
         1.5710, 1.6330, 2.3680, 2.5380, 2.3640, 2.2280, 2.2430, 2.5660, 2.9960,
         2.1600, 1.7720, 2.0660, 1.7970, 1.9160, 2.7520, 1.8760, 1.8990, 1.8390,
         1.7990, 2.2160, 2.0190, 2.4100, 1.4490, 1.8750, 2.1740, 2.3580, 1.8570,
         2.2290, 2.0360, 2.3260, 1.7820, 1.6390, 1.5710, 2.7600, 1.3300, 1.4810,
         1.8000, 2.7280, 1.6440, 2.1810, 1.9310, 1.3910, 1.6730, 1.7380, 2.0210,
         1.8060, 1.5540, 1.9210, 1.5770, 1.6210, 2.2730, 1.6970, 2.0450, 1.5910,
         2.0740, 1.8160, 2.2450, 1.6240, 1.8850, 1.8550, 2.0140, 1.5580, 1.7550,
         1.6280, 2.0880, 1.9450, 1.9780, 1.9390, 1.9080, 1.9560, 2.2320, 2.4590,
         2.1590, 2.3850, 2.2760, 1.6150, 2.1770, 2.4050, 2.3200, 2.2250, 2.3880,
         2.3460, 2.9040, 2.0870, 2.0090, 2.1450, 1.7340, 2.2220, 2.3290, 2.1380,
         2.2090, 1.8830, 1.7910, 2.5410, 1.9710, 2.3060, 2.7600, 1.9180, 2.1230,
         1.6550, 2.1290, 2.3870, 2.4750, 1.6920, 1.8340, 1.7190, 1.8330, 2.7880,
         1.4710, 1.6210, 1.9570, 2.1890, 1.6980, 2.0250, 2.6850, 1.5580, 1.8500,
         1.7030, 1.8080, 1.5930, 1.7880, 2.0190, 1.7380, 1.8720, 2.1420, 1.9690,
         1.6310, 1.9120, 2.0960, 1.8470, 2.0700, 1.5730, 1.9980, 2.1930, 1.9760,
         1.7330, 1.5740, 1.8380, 1.4570]], dtype=torch.float64)